import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const lexend = Lexend_Deca({
  subsets: ["latin"],
  variable: "--lexend-font",
  weight: ["300", "400"],
});

const beautyFont = localFont({
  src: "../public/fonts/Corinthia-Regular.ttf",
  variable: "--beauty-font",
});

export const metadata: Metadata = {
  title: "Hải Đôn & Thu Huyền",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/icon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${beautyFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
